export const SITE_CONFIG = {
  name: 'Tulsi Mahotsav 2026',
  hindiName: 'तुलसी महोत्सव 2026',
  taglineHindi: 'जहाँ शब्द उत्सव बनते हैं।',
  taglineEnglish: 'Where words become a celebration.',
  institutionHindi: 'हिंदी समिति, एम.आई.टी.एस. - डी.यू., ग्वालियर',
  institutionEnglish: 'Hindi Samiti, MITS-DU, Gwalior',
  location: 'MITS Campus, Gwalior, Madhya Pradesh',
  dates: '26 — 27 September 2026',
  datesShort: '26–27 SEPT 2026',
  registrationUrl: 'https://linktr.ee/tulsimahotsav',
  emails: {
    official: 'tulsimahotsavofficial@gmail.com',
    samiti: 'hindisamitiofficial@gmail.com',
  },
  contacts: [
    {
      name: 'Devansh Rai',
      role: 'Overall Lead / Coordinator',
      phone: '',
    },
    {
      name: 'Baldev Kaurav',
      role: 'Hindi Samiti Lead',
      email: 'hindisamitiofficial@gmail.com',
    },
  ],
  socials: {
    instagram: 'https://instagram.com',
    youtube: 'https://youtube.com',
  },
  assets: {
    dayTexture: '/assets_webp/day-texture.webp',
    texture: '/assets_webp/texture.webp',
    footer: '/assets_webp/footer.webp',
    logo: '/assets_webp/TulsiMahotsav__ Logo.webp',
    diyaLeft: '/assets_webp/diya-left-corner.webp',
    diyaRight: '/assets_webp/diya-right-corner.webp',
    flame1: '/assets_webp/flame1.webp',
    flame2: '/assets_webp/flame2.webp',
    flame3: '/assets_webp/flame3.webp',
    mandalaInner: '/assets_svg/madala-animation-inner-element.svg',
    mandalaOuter: '/assets_svg/madala-animation-outer-element.svg',
    mandalaAccents: '/assets_svg/madala-animation-micro-accents-layer-element.svg',
    leftCircle: '/assets_svg/leftCircle.svg',
    rightCircle: '/assets_svg/rightCircle.svg',
    midCircle: '/assets_svg/midCircle.svg',
    leftStrip: '/assets_svg/leftStrip.svg',
    rightStrip: '/assets_svg/rightStrip.svg',
    horizontalBorder: '/assets_svg/horizontal-ornamental-border.svg',
    monoBorder: '/assets_svg/ornamental-border-mono-colour.svg',
    headerStrip: '/assets_svg/ornamental-coloured-header-strip.svg',
    guestFrame: '/assets_webp/guest-frame.webp',
    teamFrame: '/assets_webp/team-main-frame.webp',
  },
};
